export const eventsJavaScript = [
    'window.onload = () => function(){ \nconsole.log("load"); \n};',
    'const item = document.querySelector();\nitem.addEventListener("click", function(){ \n\tconsole.log("click") \n});',
    'const item = document.querySelector();\nitem.addEventListener("dblclick", function(){ \n\tconsole.log("dblclick") \n});',
    'const item = document.querySelector();\nitem.addEventListener("keydown", function(){ \n\tconsole.log("ketkeydown") \n});',
    'const item = document.querySelector();\nitem.addEventListener("mousemove", function(){ \n\tconsole.log("mousemove") \n});',
    'const item = document.querySelector();\nitem.addEventListener("input", function(){ \n\tconsole.log("input") \n});',
    'const img = document.querySelector("img");\nitem.addEventListener("load", function(){ \n\tconsole.log("load") \n});',
    'const img = document.querySelector("img");\nitem.addEventListener("error", function(){ \n\tconsole.log("error") \n});',
    'const form = document.querySelector("form");\nitem.addEventListener("submit", function(){ \n\tconsole.log("submit") \n});',
    'const select = document.querySelector("select");\nitem.addEventListener("change", function(){ \n\tconsole.log("change") \n});',
    'const element = document.querySelector();\nitem.addEventListener("mouseover", function(){ \n\tconsole.log("mouseover") \n});',
    'const checkbox = document.querySelector("checkbox");\nitem.addEventListener("checked", function(){ \n\tconsole.log("checked") \n});',
    'const ul = document.querySelector("ul");\nitem.addEventListener("click", function(){ \n\tconsole.log("click") \n});'
];

export const functionsJavaScript = [
    'const item = document.createElement(); \nitem.textContetn = "create";',
    'document.querySelector().remove();',
    'const item = document.querySelector(); \nitem.textContent = "create"; \ndocument.querySelector("parent").append(item);',
    'const item = document.querySelector(); \nitem.textContent = "create"; \ndocument.querySelector("parent").prepend(item);',
    'const item = document.querySelector(); \nitem.textContent = "create"; \nconst child = document.querySelector("child"); \nchild.parentNode.inserBefore(item, child.nextSibling);',
    'const item = document.querySelector(); \nitem.textContent = "create"; \nconst child = document.querySelector("child"); \nchild.parentNode.inserBefore(item, child);',
    'const item = document.querySelector(); \nitem.cloneNode();',
    'const item = document.querySelector(); \nitem.classList.add("class");',
    'const item = document.querySelector(); \nitem.classList.remove("class");',
    'const item = document.querySelector(); \nitem.classList.toggle("class");',
    'const item = document.querySelector("button"); \nitem.setAttribute("disabled", true);',
    'const item = document.querySelector("button"); \nitem.removeAttribute("disabled");',
    'const item = document.querySelector("img"); \nitem.setAttribute("data-src", url);',
    'const item = document.querySelector("img"); \nitem.removeAttribute("data-src");',
    'const item = document.querySelector(); \nitem.style.display = "none";',
    'const item = document.querySelector(); \nitem.style.display = "block";',
    '',
    '',
    'const items = document.querySelectorAll(); \nitems.foreach(item => (){\n\titem.style.color = red; \n});',
    'const item = document.querySelector(); \nitem.parentNode.style.font-weight = 300;',
    'const items = document.querySelector(); \nitems.children.foreach(child => (){ \n\tchild.style.font-weight = 300; \n});',
    'const items = document.querySelectorAll(".class"); \nitems.foreach(item => (){ \n\titem.style.font-weight = 300; \n});',
    'const item = document.getElementById("id"); \nitem.style.font-weight = 300;',
    'const items = document.querySelectorAll(".class"); \nitems.foreach(item => (){ \n\tif(item.style.display == "none"){ \n\t\titem.style.color = red; \n\t\titem.style.dispaly = visible;\n\t}\n});',
    'const select = document.querySelector("select"); \nselect.options[select.selectedIndex].value;',
    'const item = document.querySelector("a"); \nitem.setAttribute("href", "url");',
    'alert(document.querySelector("input").value);',
    'const selector = document.querySelector("selector"); \nfor(let i = 0; i < selector.options.length -1; i++) select.remove(i);',
    'with css is better'
];
